export interface MeterSettings {enabled:boolean;host:string;port:number;device_id:number}
export interface MeterReading {online:boolean;timestamp:number;error:string|null;power_kw?:number;currents_a?:number[];voltages_v?:number[];phase_powers_kw?:number[]}
export interface Settings {meter:MeterSettings;site_name:string; power_limit_kw:number; phase_limit_a:number;power_tolerance_pct:number; reserve_kw:number; fallback_building_kw:number; rotation_seconds:number; ramp_up_seconds:number; restart_delay_seconds:number; paused:boolean}
export interface Simulation {building_kw:number;profile:'balanced'|'uneven';meter_online:boolean;disconnected:string[];offline:string[]}
export interface LocalStartResult {id:string;status:'pending'|'accepted'|'failed'|'uncertain';message:string;ok:boolean;applied_at:number}
export interface Station {state?:number;local_start_configured?:boolean;local_start_result?:LocalStartResult|null;id:string;name:string;model:'P30 x'|'P40';max_current_a:number;installation_limit_a?:number;device_limit_a?:number|null;hardware_limit_a?:number|null;adaptive_limit_a?:number;unused_grant_a?:number;commanded_current_a?:number;target_current_a?:number;control_reason?:string;priority:'normal'|'high';paused:boolean;host:string;port:number;device_id:number;connected:boolean;online:boolean;network_online?:boolean;phases:number[];phase_count?:number|null;phase_switch_source?:number|null;currents_a?:number[];voltages_v?:Array<number|null>;current_a:number;power_kw:number;power_factor_pct?:number|null;session_kwh:number;energy_kwh?:number;rfid_uid?:string|null;serial?:number|null;product_raw?:number|null;firmware?:string|null;firmware_raw?:number|null;hardware_revision?:number|null;meter_hardware_revision?:number|null;failsafe_current_a?:number|null;failsafe_timeout_s?:number|null;fast_charging?:boolean|null;error_code?:number|null;web_url?:string;connection_detail?:string;control_error?:string|null;status:'charging'|'paused'|'available'|'safe'|'waiting'|'offline'|'setup'}
export interface State {mode:string;status:string;timestamp:number;meter_timestamp:number;site_name:string;settings:Settings;stations:Station[];simulation:Simulation;building_kw:number;charging_kw:number;estimated_charging_kw?:number;total_kw:number;phase_currents_a:number[];headroom_kw:number;meter_online:boolean;building_source?:'meter'|'fallback'|'simulation'|'unavailable'|'hold';meter?:MeterReading;measurement_error?:string|null;power_ceiling_kw?:number;building_currents_a?:number[];manual_start_ids?:string[];revision:number;overload:boolean;monta_status:string;commissioned:boolean}
export interface Sample {ts:number;building_kw:number;charging_kw:number;total_kw:number}
export interface Event {id:number;ts:number;level:string;message:string}
